In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros(15,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones(15,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [9]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.random.rand(3,2)

array([[0.93607409, 0.47303742],
       [0.79575109, 0.246216  ],
       [0.87981814, 0.08554093]])

In [13]:
np.random.randn(3,2)

array([[ 0.60641375, -0.55730087],
       [-0.98016782,  0.21249534],
       [ 0.33506141,  0.21973919]])

In [14]:
np.random.randint(34,100)

59

In [15]:
np.random.randint(20,56,100)

array([42, 21, 38, 30, 22, 46, 54, 25, 37, 48, 31, 24, 25, 38, 24, 31, 40,
       26, 23, 39, 23, 43, 32, 49, 45, 41, 22, 30, 54, 32, 25, 20, 24, 22,
       55, 37, 46, 55, 31, 43, 40, 29, 48, 46, 51, 25, 40, 28, 51, 54, 35,
       46, 33, 42, 43, 45, 38, 48, 39, 32, 37, 39, 40, 29, 44, 29, 25, 48,
       36, 38, 28, 38, 28, 50, 20, 53, 43, 34, 20, 35, 37, 31, 21, 45, 32,
       51, 32, 49, 47, 51, 25, 45, 47, 39, 47, 54, 23, 41, 35, 44])

In [17]:
rand_array = np.random.randint(23,100,4)

In [18]:
rand_array

array([86, 83, 52, 37])

In [19]:
rand_array.min()

37

In [20]:
rand_array.argmin()

3

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.T

AttributeError: ignored

In [25]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
b=a.reshape(5,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [29]:
b.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [32]:
a[-3]

27

In [33]:
a[3:7]

array([3, 4, 5, 6])

In [34]:
sample_matrix=np.array(([50,20,10,3],[24,31,43,21],[32,22,65,76]))

In [35]:
sample_matrix

array([[50, 20, 10,  3],
       [24, 31, 43, 21],
       [32, 22, 65, 76]])

In [36]:
sample_matrix[1][2]

43

In [37]:
sample_matrix[2]

array([32, 22, 65, 76])

In [38]:
sample_matrix[2,:]

array([32, 22, 65, 76])

In [40]:
sample_matrix[:,(3,2)]

array([[ 3, 10],
       [21, 43],
       [76, 65]])

In [41]:
np.square(a)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [42]:
np.mean(a)

14.5

In [44]:
c = np.random.randn(5,6)
c

array([[ 1.91928442,  0.34434865, -1.24225972,  0.41618225, -0.5684297 ,
         0.31680602],
       [-0.24342572,  1.13524895,  0.5971233 , -0.45792655, -0.1696226 ,
         0.12556999],
       [ 0.98450143,  2.42923835,  0.15154157,  0.1392346 ,  0.64805201,
        -0.50542854],
       [-1.16457341,  0.54755557, -0.61271987,  0.35474155,  1.1887229 ,
         0.15070508],
       [-1.2190225 ,  0.59987553,  0.86345458,  0.50492533,  1.73214334,
         0.51426238]])

In [45]:
np.round(c,decimals=3)

array([[ 1.919,  0.344, -1.242,  0.416, -0.568,  0.317],
       [-0.243,  1.135,  0.597, -0.458, -0.17 ,  0.126],
       [ 0.985,  2.429,  0.152,  0.139,  0.648, -0.505],
       [-1.165,  0.548, -0.613,  0.355,  1.189,  0.151],
       [-1.219,  0.6  ,  0.863,  0.505,  1.732,  0.514]])

In [48]:
sports = np.array(['golf','cricket','fball','fball','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')